query: topic:nomad stars:>30 archived:false
ignore_reason: ALWAYS IGNORE PROJECTS IN THE DESCRIPTION OF WHICH HASHICORP NOMAD IS NOT MENTIONED!
root:
  categories:
    - title: Documentation, examples, demos and awesome lists
      prompt: Documentation, guides, tutorials, how-tos, examples, demos, and awesome lists for Nomad
    - title: Infrastructure setup
      prompt: Tools and utilities for setting up Nomad infrastructure
    - title: Ops tools
      prompt: Solutions for operators to manage and maintain Nomad infrastructures in day-to-day operations
    - title: DevOps tools
      prompt: Tools and utilities for DevOps
    - title: CI / CD
      prompt: Continuous Integration and Continuous Deployment tools and utilities
    - title: Integrations
      prompt: Integrations with other tools and services
    - title: Plugins
      prompt: Plugins and extensions for Nomad
    - title: SDK
      prompt: Software Development Kits for Nomad
